### ISSUE TITLE
Configuração do Ambiente 

### ISSUE THREAD

**Issue by marcelorosasalves** [IFAMAZONAS/EngenhariaSW#11]
Nesta Issues será realizado a configuração do ambiente de programação e das ferramentas necessárias para o desenvolvimento do sistema.

**Comment by ifamfagner** [comment]
Em andamento.. Aguardando o banco de dados, ficar pronto

**Comment by marcelorosasalves** [comment]
Realizado a configuração do Ambiente de Desenvolvimento(Eclipse), integrado com o repositório do GitHub. 
Revisado e finalizado em 11/12/18.
