### ISSUE TITLE
Cadastro de Clientes

### ISSUE THREAD

**Issue by marcelorosasalves** [IFAMAZONAS/EngenhariaSW#14]

**Comment by ifamfagner** [comment]
Finalizada. Conforme deploy no Heruko  https://sistema-locadora.herokuapp.com/home

**Comment by paulolins-ufpe** [comment]
1. Excluir entidades fraca do banco de dados. Ao tentar desativar um cliente o mesmo
deve ocorrer para seus dependentes. Não estava funcionando desta forma, de maneira
automática (em cascata). Para resolver foi acionada a anotação
@OneToMany(mappedBy = &quot;idCliente&quot;, cascade = {CascadeType.ALL}, fetch =
FetchType.LAZY) na Classe Cliente. Sendo assim, todas as operações de persistência na
Entidade Cliente refletem-se à Entidade Dependente.

1. Expressão regular para o padrão de Mascaras de Telefones, CPF no cadastro de
cliente e usuário. Pelo pouco de conhecimento na linguagem Java Script demorou-se a
resolver o problema IMPLANTAÇÃO DA VERSÃO EM PRODUÇÃO.
