### ISSUE TITLE
TDD- (#37)-Maximo de 3 Dependentes por Cliente [RN07]

### ISSUE THREAD

**Issue by marcelorosasalves** [IFAMAZONAS/EngenhariaSW#18]

**Comment by marcelorosasalves** [comment]
O issues não foi concluída devido a dificuldade no uso das ferramentas, sendo necessário um estudo mais aprofundado sobre as mesmas.
Essa issues passará para a próxima Sprint

**Comment by paulolins-ufpe** [comment]
Atividade
[#37](https://github.com/IFAMAZONAS/EngenhariaSW/issues/37)

**Comment by paulolins-ufpe** [comment]
Teste Funcional :#37
![tdd -dependentes](https://user-images.githubusercontent.com/45341539/51988671-a8052e80-247b-11e9-8956-2e1d613ce128.jpg)
