### ISSUE TITLE
Implantação da release do 2º sprint no servidor Heroku

### ISSUE THREAD

**Issue by marcelorosasalves** [IFAMAZONAS/EngenhariaSW#20]

**Comment by ifamfagner** [comment]
Primeira release do sistema implantado no servisdor. Acesso em https://sistema-locadora.herokuapp.com/home

**Comment by paulolins-ufpe** [comment]
Erro no servidor de aplicação Heroku, aplicação roda no Ambiente de
Desenvolvimento no Eclipse, porém ao realizar o deploy no Heroku a mesma não
funciona. Após muitas pesquisas a fóruns e sites da área, o problema foi resolvido
alterando no nome de páginas, pois as que estavam apresentado erro eram páginas que
tinhas caracteres maiúsculos em sua escrita. Esse problema não foi identificado no
início, pois no ambiente de desenvolvimento a aplicação funcionava de forma perfeita,
porém ao realizar o build, o mesmo era finalizado com sucesso, no entanto às páginas
não funcionavam.
Resolvido!
