### ISSUE TITLE
Implantação da release do 3º sprint no servidor Heroku

### ISSUE THREAD

**Issue by marcelorosasalves** [IFAMAZONAS/EngenhariaSW#21]

**Comment by ifamfagner** [comment]
Demanda realizada por meio do deploy da aplicação no Heruko acesso em https://sistema-locadora.herokuapp.com/

**Comment by paulolins-ufpe** [comment]
Após o termino da implementação da parte de autenticação de usuários, criação de papéis e regras com a solução Spring Security foi testado o sistema no ambiente local de desenvolvimento e funcionou perfeitamente. Porém ao realizar a implantação no servidor Heroku em produção, ao realizar o login conforme a imagem 1, após consultas ao Log do Heroku verificou que a versão do PostgreSQL usada pela aplicação local estava em uma versão diferente da instalada no servidor.  
![image](https://user-images.githubusercontent.com/45341539/52804012-50191b00-306a-11e9-9ed3-b781d6d909f5.png)
Para solucionar o problema foi corrigido as bibliotecas que acessam o banco de dados no arquivo pom.xml do Maven, conforme imagem 2.  Desta forma o sistema busca a versão mais atual do banco, com  procedimento o sistema voltou a funcionar perfeitamente.
![image](https://user-images.githubusercontent.com/45341539/52804030-59a28300-306a-11e9-8377-43ecb3d2e9a5.png)
