### ISSUE TITLE
TDD- (#44)-Desativar o Cliente e seus Dependentes [RN05]

### ISSUE THREAD

**Issue by marcelorosasalves** [IFAMAZONAS/EngenhariaSW#22]

**Comment by paulolins-ufpe** [comment]
Teste Unitário da Regra: #44

**Comment by paulolins-ufpe** [comment]
Teste Funcional :#44
O teste visa garantir à Regra de Negócio [RN05] em que a aplicação Desativa o Cliente e seus Dependentes caso os tenham , para a realização deste Teste Funcional, usou-se o framework JUnit para criação de testes automatizados.
O teste foi realizado diretamente no código da aplicação, com a finalidade de criar o objeto Cliente e seus Dependentes e ao se passar o Cliente com Id NULL o método retorna False e True quando o conseguir mudar os status para INATIVO do Cliente juntamento com seus Dependentes.

![tdd 44- desativar clientes e dependentes](https://user-images.githubusercontent.com/45341539/52666982-0f909480-2ee6-11e9-9f63-f5e809dda6e5.jpg)
