### ISSUE TITLE
CRUD  de Usuários

### ISSUE THREAD

**Issue by marcelorosasalves** [IFAMAZONAS/EngenhariaSW#26]
- Cadastro de Usuários
- Atualização de Usuários
- Associação de Usuários ao perfis 
- Controle de Acesso

**Comment by ifamfagner** [comment]
Finalizado! Conforme deploy no Heruko https://sistema-locadora.herokuapp.com/home

**Comment by ifamfagner** [comment]
Demanda finalizada, foi implementa com spring security o controle de acesso por papeis. Criado Funcões para o cadastro de usuário e gestão de permissões
