### ISSUE TITLE
TDD- (#45)-Reativar os Clientes e seus Dependentes [RN11]

### ISSUE THREAD

**Issue by marcelorosasalves** [IFAMAZONAS/EngenhariaSW#28]

**Comment by paulolins-ufpe** [comment]
A data de devolução prevista e definida em função do filme do item ser lançamento ou não, caso seja lançamento o prazo e 1 dia e de 3 dias para catalago.

**Comment by paulolins-ufpe** [comment]
Teste Unitário da Regra: #45

**Comment by paulolins-ufpe** [comment]
Teste Funcional : #47

O sistema deve permitir reativar seus clientes e dependentes.
![tdd- 47](https://user-images.githubusercontent.com/45341539/52748452-f0186b00-2fbc-11e9-80e7-cda14cab707b.jpg)
