### ISSUE TITLE
BDD- (#46)-Controle de Acesso as Funcionalidades [RNF01]

### ISSUE THREAD

**Issue by marcelorosasalves** [IFAMAZONAS/EngenhariaSW#29]

**Comment by paulolins-ufpe** [comment]
#46

**Comment by paulolins-ufpe** [comment]
Testes de Aceitação da [RNF01] - O sistema deve controlar as funcionalidades para controlar o acervo, devendo estas funcionalidades serem restritas a Administradores.

![image](https://user-images.githubusercontent.com/45341539/52746922-058b9600-2fb9-11e9-9c55-8758695f78f6.png)

**Comment by paulolins-ufpe** [comment]
Teste Finalizado.
