### ISSUE TITLE
Corrigir entrada campo CPF. Criar Mascaras

### ISSUE THREAD

**Issue by ifamfagner** [IFAMAZONAS/EngenhariaSW#34]

**Comment by mrogerio18** [comment]
Incluir a correção da mascara dos campos telefone também, tanto do cliente quanto do dependente no cadastro de clientes.
![telaerrorcadastroclientemascara](https://user-images.githubusercontent.com/16197553/50550637-92b59e00-0c4a-11e9-97db-b7485854e73d.jpg)

**Comment by ifamfagner** [comment]
Demanda realizada no commit https://github.com/IFAMAZONAS/Locadora/commit/0943e0fdc33f563d351a046f47324191410e38e3
