### ISSUE TITLE
Correção no cadastro de Clientes

### ISSUE THREAD

**Issue by mrogerio18** [IFAMAZONAS/EngenhariaSW#36]
Correção no cadastro de Clientes, no campo celular, tem uma validação do campo, que pede que seja digitado o dado no formato exigido, mesmo digitando o número do telefone no formato adequado, ao clicar no botão salvar.

**Comment by ifamfagner** [comment]
Demanda realizada no commit https://github.com/IFAMAZONAS/Locadora/commit/0943e0fdc33f563d351a046f47324191410e38e3
