### ISSUE TITLE
BDD- (#47)-Cadastro de Clientes(Campos em Brancos) [TC01]

### ISSUE THREAD

**Issue by marcelorosasalves** [IFAMAZONAS/EngenhariaSW#39]

**Comment by paulolins-ufpe** [comment]
Teste de Aceitação da Regra:#47

**Comment by paulolins-ufpe** [comment]
Teste Funcional : #47

O sistema deve permitir reativar  seus clientes e dependentes.
![tdd- 47](https://user-images.githubusercontent.com/45341539/52748191-3faa6700-2fbc-11e9-9743-c4076b6b707d.jpg)

**Comment by paulolins-ufpe** [comment]
Teste Funcional :#47
O teste verificou se ao cadastrar o Cliente os seus campos estão preenchidos, caso contrário não realiza o cadastro.
![bdd13](https://user-images.githubusercontent.com/45341539/52752966-31177c00-2fcb-11e9-8102-c800a1c69d65.jpg)
