### ISSUE TITLE
BDD- (#48)-Calculo do Acrescimo de 50% na midia Lançamento [RN11]

### ISSUE THREAD

**Issue by marcelorosasalves** [IFAMAZONAS/EngenhariaSW#41]

**Comment by LDamin** [comment]
Teste de BDD para verificação do calculo do acréscimo de 50% sobre o valor da mídia caso seja lançamento.


![image](https://user-images.githubusercontent.com/44165004/52722713-f2fa6800-2f8a-11e9-9016-1203a85da814.png)
