### ISSUE TITLE
Correção do Cadastro de Fornecedores

### ISSUE THREAD

**Issue by mrogerio18** [IFAMAZONAS/EngenhariaSW#43]
Na tela de cadastro de fornecedores, nos campos CNPJ e Telefones, precisa incluir mascara de entrada de dados, para restringir a digitação de dados incorreto.
![telaerrorcadastrofornecedoresmascara](https://user-images.githubusercontent.com/16197553/51261538-331bfa00-198f-11e9-8b63-8b4cfb29199d.jpg)

**Comment by gabrielclavilasoares** [comment]
Foi inserido as mascaras dos campos do CNPJ e Telefone, além disso foi incluída a verificação se o CNPJ já foi cadastrado anteriormente não permitindo cadastrar o mesmo CNPJ.
