### ISSUE TITLE
[RN05]Desativar Cliente e seus Dependentes

### ISSUE THREAD

**Issue by paulolins-ufpe** [IFAMAZONAS/EngenhariaSW#44]
Ao desativar o Cliente, os seus dependentes também não podem mais alocar nenhuma filme na locadora Imperial, esta funcionalidade é uma regra de negócio solicitada pelo Cliente.

**Comment by ifamfagner** [comment]
Demanda realizada,

- No Controller de Clientes, ao ser desativado um Cliente, a ação e aplicada a todos os seus dependentes.
- Funcionalidade disponível me produção.
