### ISSUE TITLE
[RN12] - Data de Devolução prevista

### ISSUE THREAD

**Issue by paulolins-ufpe** [IFAMAZONAS/EngenhariaSW#45]
Esta funcionalidade deve acrescentar ao prazo os dias estipulados, conforme o filme alocado.
Exemplo: 
 - Lançamento :1 dia
 - Catálogo : 3 dias

**Comment by ifamfagner** [comment]
Demanda realizada disponível em produção.
![image](https://user-images.githubusercontent.com/45543610/52973808-b917d000-3395-11e9-8011-25daab110770.png)

**Comment by ifamfagner** [comment]
Finalizado.
