### ISSUE TITLE
[RNF01] Controle de Acesso ao Sistema Locadora Imperial

### ISSUE THREAD

**Issue by paulolins-ufpe** [IFAMAZONAS/EngenhariaSW#46]
O  sistema deve  controlar o acesso às funcionalidades. Funcionalidades para controlar o acervo da locadora devem ser restritas a administradores. Funcionalidades de atendimento a  clientes devem estar restritas a atendentes. Funcionalidades de  consulta ao acervo devem estar disponíveis na Internet.

**Comment by ifamfagner** [comment]
Funcionalidade implementada, disponível no Heroku
