### ISSUE TITLE
[RN11] Calculo de Acrescimo de 50% da Midia Lançamento

### ISSUE THREAD

**Issue by paulolins-ufpe** [IFAMAZONAS/EngenhariaSW#48]
O valor da locação de um item é dado pelo tipo de mídia do item. Cada tipo de mídia tem um valor de locação associado. Um acréscimo de 50% do valor da locação do tipo de mídia deve ser aplicado no caso do filme do item ser um lançamento.

**Comment by ifamfagner** [comment]
Demanda realizada, encontra-se em produção.

- Ao ser cadastrado um filme,  foi adicionado a verificação no Controller de Filme.
- Se o mesmo for lançamento, o seu valor de locação sofre um reajuste de 50%. Funcionalidade disponível em produção.
