### ISSUE TITLE
[BUG]-Carregamento da Data do Filme

### ISSUE THREAD

**Issue by paulolins-ufpe** [IFAMAZONAS/EngenhariaSW#49]
Ao editar qualquer filme a data de aquisição cadastrada no banco de dados não é retornada.
![erro -botao visualizar](https://user-images.githubusercontent.com/45341539/51749169-08176180-2085-11e9-9214-7e5b1c0cde45.jpg)

**Comment by mrogerio18** [comment]
1. Nesta tela de cadastro de filmes, incluir acentuação gráfica na legendo do Campo Gênero e Tipo de Mídia. 
2. Na legenda Duração, sugiro alterar para Duração (em minutos).

**Comment by ifamfagner** [comment]
Não será implementado nessa versão a opção de editar, está com erro no editar, porém não foi possível identificá-lo a tempo.
