### ISSUE TITLE
[BUG]-Botão Visualizar permite Editar o filme

### ISSUE THREAD

**Issue by paulolins-ufpe** [IFAMAZONAS/EngenhariaSW#50]
Ao se clicar no botão no visualizar é possível também editar o filme e salvar, no entanto, deveria somente permitir a visualização do filme não edição e salvar.
![erro -botao visualizar 2](https://user-images.githubusercontent.com/45341539/51749436-b7eccf00-2085-11e9-8130-24166ba94588.jpg)

**Comment by ifamfagner** [comment]
Problema resolvido. Solução implementada. Com a opção visualizar filme.
