### ISSUE TITLE
[BUG] - Cadastro Fornecedor sem Mascaras de Validação

### ISSUE THREAD

**Issue by paulolins-ufpe** [IFAMAZONAS/EngenhariaSW#51]
Ao se cadastrar um fornecedor é permitido inserir os dados sem máscaras, sem validação no banco de dados.
![erro -fornecedor sem mascaras](https://user-images.githubusercontent.com/45341539/51749779-b2dc4f80-2086-11e9-9780-8f892dd958c4.jpg)

**Comment by mrogerio18** [comment]
Na tela de listar fornecedores é preciso corrigir o nome da legenda Fornecedor que ficou errado.
![correcaotelalistarfornecedores](https://user-images.githubusercontent.com/16197553/51785512-c0054700-2137-11e9-8c27-686c4ee8ffb6.png)

Link: https://sistema-locadora.herokuapp.com/fornecedor/listarfornecedor

**Comment by ifamfagner** [comment]
Demanda realizada em conjunto com o Gabriel, já se encontra em produção a correção.


- Foram criadas as Mascarás com JavaScript
- Foram adicionados nos Controladores as validações necessárias.
