### ISSUE TITLE
[BUG]-Cadastro de Dependentes

### ISSUE THREAD

**Issue by paulolins-ufpe** [IFAMAZONAS/EngenhariaSW#52]
No cadastro de Dependentes foram encontrados os seguintes problemas:
Data de Nascimento
  -É permitido cadastrar um dependente em branco;
  -Falta de máscara e Validação, permite colocar qualquer valor;
Botão Editar 
 - Ao se clicar no botão de editar dos Dependentes, não acontece nada;
![erro -dependentes](https://user-images.githubusercontent.com/45341539/51750393-567a2f80-2088-11e9-81cd-fa4006fe0025.jpg)

**Comment by ifamfagner** [comment]
Essa funcionalidade não será implementada nesta entrega. Fica como customização para as proximas versões
