### ISSUE TITLE
[BUG] - Cadastro de Filmes

### ISSUE THREAD

**Issue by paulolins-ufpe** [IFAMAZONAS/EngenhariaSW#53]
Ao tentar cadastrar filmes com sinopse , informa este erro:
![erro -cadastro de filmes-data](https://user-images.githubusercontent.com/45341539/51752350-a8718400-208d-11e9-996f-b95d0fc8c9fe.jpg)

**Comment by ifamfagner** [comment]
Resolvido, o problema era que no servidor heroku ao ser criado o Banco definia o tamanho do campo Sinopse apenas com 200 caracteres.  Foi ajustado no banco para 200000
