### ISSUE TITLE
[BUG] - Botão Editar do Cadastro de Filme, não funciona.

### ISSUE THREAD

**Issue by paulolins-ufpe** [IFAMAZONAS/EngenhariaSW#54]
O botão editar do cadastro de Filmes, não está funcionando. Só carrega a tela, sem carregar as informações de qualquer filme.

**Comment by paulolins-ufpe** [comment]
O botão editar do cadastro de Filmes, não está funcionando. Só carrega a tela, sem carregar as informações de qualquer filme.

**Comment by ifamfagner** [comment]
Demanda realizada, disponível em produção.
