### ISSUE TITLE
[BUG] -Cadastro do Fornecedor - Tratar Campos em branco

### ISSUE THREAD

**Issue by mrogerio18** [IFAMAZONAS/EngenhariaSW#57]
Na alteração do cadastro de fornecedor, ao salvar se deixar um campo em branco, é necessário fazer o tratamento do erro.

**Comment by ifamfagner** [comment]
Não será realizada esta demanda, para não comprometer o uso do sistema foi retirado o botão editar da tela. Estava com erro, e não foi possível finalizá-la
