### ISSUE TITLE
Incluir link dos videos para ajudar nas atividades operacionais do usuário

### ISSUE THREAD

**Issue by mrogerio18** [IFAMAZONAS/EngenhariaSW#58]
Cadastrar Clientes
https://youtu.be/aHyixgWbWxE

Cadastrar Filmes
https://youtu.be/tMGhyltJBSk

Cadastrar Fornecedor
https://youtu.be/eBpadyWtAG4

Cadastrar Locação
https://youtu.be/tKrmydnGPnw

Cadastrar Usuários
https://youtu.be/OEHIcQouBpc

**Comment by paulolins-ufpe** [comment]
Atividade Finalizada.
* Página Principal do Wiki : https://github.com/IFAMAZONAS/EngenhariaSW/wiki
* Acesse o Link: <a href="https://github.com/IFAMAZONAS/EngenhariaSW/wiki">Ajuda </a>
* Para os vídeos, acesse o : https://github.com/IFAMAZONAS/EngenhariaSW/wiki/Ajuda.
